spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

jwt:
  secret: ${JWT_SECRET}

cookie:
  same-site: None
  secure: true