spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

jwt:
  secret: ${JWT_SECRET}

cookie:
  same-site: None
  secure: true